# Generated by Django 4.0.3 on 2022-03-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mband', '0003_rename_link_linkvk_linkyt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Нет статуса'), ('searching for group', 'В поисках группы'), ('searching for people', 'В поисках людей в группу')], max_length=64),
        ),
    ]
