# Generated by Django 4.0.3 on 2022-03-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mband', '0005_alter_linkvk_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='linkvk',
            options={'verbose_name': 'Сыллка Vkontakte', 'verbose_name_plural': 'Ссылки Vkontakte'},
        ),
        migrations.AlterModelOptions(
            name='linkyt',
            options={'verbose_name': 'Сыллка Youtube', 'verbose_name_plural': 'Ссылки Youtube'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='users',
            new_name='user',
        ),
    ]
