# Generated by Django 4.0.3 on 2022-03-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mband', '0006_alter_genre_options_alter_linkvk_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkyt',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='linkVK',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkYT',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.DeleteModel(
            name='LinkVK',
        ),
        migrations.DeleteModel(
            name='LinkYT',
        ),
    ]
