# Generated by Django 4.0.3 on 2022-04-06 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mband', '0009_alter_genre_user_alter_profile_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='region',
            new_name='discrict',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
