# Generated by Django 4.0.3 on 2022-04-06 21:24

from django.db import migrations, models
import mband.models


class Migration(migrations.Migration):

    dependencies = [
        ('mband', '0012_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=mband.models.upload_to, verbose_name='Image'),
        ),
    ]
