# Generated by Django 4.0.3 on 2022-04-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mband', '0014_remove_profile_photo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(blank=True, choices=[('Фолк', 'Фолк'), ('Рок', 'Рок'), ('Рэп', 'Рэп'), ('Металл', 'Металл'), ('Классика', 'Классика')], max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Нет статуса', 'Нет статуса'), ('В поисках группы', 'В поисках группы'), ('В поисках людей в группу', 'В поисках людей в группу')], default=('Нет статуса', 'Нет статуса'), max_length=64),
        ),
    ]
